// <auto-generated />
using System;
using CalculoImposto.API.Banco;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculoImposto.API.Migrations
{
    [DbContext(typeof(CalculoImpostoContext))]
    [Migration("20240315125036_PrimeiraMigracao")]
    partial class PrimeiraMigracao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalculoImposto.API.Model.INSS.INSSModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("datetime2");

                    b.Property<int>("Faixa")
                        .HasColumnType("int");

                    b.Property<decimal>("Porcentagem")
                        .HasColumnType("DECIMAL(7,4)");

                    b.Property<decimal>("Teto")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.ToTable("INSS");
                });

            modelBuilder.Entity("CalculoImposto.API.Model.IRRF.DependenteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("DATETIME");

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Dependentes");
                });

            modelBuilder.Entity("CalculoImposto.API.Model.IRRF.DescontoMinimoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("DATETIME");

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.ToTable("DescontoMinimos");
                });

            modelBuilder.Entity("CalculoImposto.API.Model.IRRF.IRRFModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Deducao")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("Faixa")
                        .HasColumnType("int");

                    b.Property<decimal>("Porcentagem")
                        .HasColumnType("DECIMAL(7,4)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.ToTable("IRRF");
                });

            modelBuilder.Entity("CalculoImposto.API.Model.IRRF.SimplificadoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("DATETIME");

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Simplificados");
                });
#pragma warning restore 612, 618
        }
    }
}
