// <auto-generated />
using System;
using CalculoImposto.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculoImposto.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250321140037_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalculoImposto.Domain.Entities.Dependente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Competence")
                        .HasColumnType("DATE");

                    b.Property<decimal>("Value")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Dependente", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8738c50-3292-4ecb-af01-57cb7d62f97a"),
                            Competence = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 189.59m
                        });
                });

            modelBuilder.Entity("CalculoImposto.Domain.Entities.DescontoMinimo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Competence")
                        .HasColumnType("DATE");

                    b.Property<decimal>("Value")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.ToTable("DescontoMinimo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7f1b5cb3-cc50-4b61-a069-23c8405ff803"),
                            Competence = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 10m
                        });
                });

            modelBuilder.Entity("CalculoImposto.Domain.Entities.Inss", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Competence")
                        .HasColumnType("DATE");

                    b.Property<decimal>("Percent")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<int>("Range")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Inss", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d1b0e2f-fb2e-4bca-a16a-cda0ee17b065"),
                            Competence = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 7.5m,
                            Range = 1,
                            Value = 1045.00m
                        },
                        new
                        {
                            Id = new Guid("122b3a2e-3c79-4348-9242-ac850e0c4a32"),
                            Competence = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 9m,
                            Range = 2,
                            Value = 2089.60m
                        },
                        new
                        {
                            Id = new Guid("14c8001b-7cd8-410e-ab7f-a93662b3989f"),
                            Competence = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 12m,
                            Range = 3,
                            Value = 3134.40m
                        },
                        new
                        {
                            Id = new Guid("21a3f856-5d86-453d-b0ae-6181be43df06"),
                            Competence = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 14m,
                            Range = 4,
                            Value = 6101.06m
                        },
                        new
                        {
                            Id = new Guid("29628231-f502-4915-acc9-0586be47a9e8"),
                            Competence = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 7.5m,
                            Range = 1,
                            Value = 1100.00m
                        },
                        new
                        {
                            Id = new Guid("30144cb3-8953-452e-8df4-38a49192fd0c"),
                            Competence = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 9m,
                            Range = 2,
                            Value = 2203.45m
                        },
                        new
                        {
                            Id = new Guid("37e3a79f-8fad-4d56-9c74-90d71677f81e"),
                            Competence = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 12m,
                            Range = 3,
                            Value = 3305.22m
                        },
                        new
                        {
                            Id = new Guid("39ff5d25-7edb-463a-8321-a41bdda2fc34"),
                            Competence = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 14m,
                            Range = 4,
                            Value = 6433.57m
                        },
                        new
                        {
                            Id = new Guid("3e2f48e0-0383-4e83-ac00-146830b3d4a5"),
                            Competence = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 7.5m,
                            Range = 1,
                            Value = 1212.00m
                        },
                        new
                        {
                            Id = new Guid("493755aa-215d-4b58-a89e-c64149aa195d"),
                            Competence = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 9m,
                            Range = 2,
                            Value = 2452.67m
                        },
                        new
                        {
                            Id = new Guid("59c34449-05ad-4d37-8e31-0a6b8919d784"),
                            Competence = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 12m,
                            Range = 3,
                            Value = 3679.00m
                        },
                        new
                        {
                            Id = new Guid("6c8bfacf-b487-45f0-9fac-07019f049b65"),
                            Competence = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 14m,
                            Range = 4,
                            Value = 7087.22m
                        },
                        new
                        {
                            Id = new Guid("71918e26-9e1a-45be-b506-eef4c4d8fde3"),
                            Competence = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 7.5m,
                            Range = 1,
                            Value = 1302.00m
                        },
                        new
                        {
                            Id = new Guid("7df80acf-f350-4678-afc6-24b579494b72"),
                            Competence = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 9m,
                            Range = 2,
                            Value = 2571.29m
                        },
                        new
                        {
                            Id = new Guid("9cecf50d-d733-41a6-bc36-44d6fcc1b58c"),
                            Competence = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 12m,
                            Range = 3,
                            Value = 3856.94m
                        },
                        new
                        {
                            Id = new Guid("a9247c53-f0f5-4894-9c08-9b47f439a36a"),
                            Competence = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 14m,
                            Range = 4,
                            Value = 7507.49m
                        },
                        new
                        {
                            Id = new Guid("b2a14b29-cc63-4c87-8c73-18a2807aa080"),
                            Competence = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 7.5m,
                            Range = 1,
                            Value = 1320.00m
                        },
                        new
                        {
                            Id = new Guid("b4e4897a-273c-4818-8767-01ca459804b1"),
                            Competence = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 9m,
                            Range = 2,
                            Value = 2571.29m
                        },
                        new
                        {
                            Id = new Guid("cb0473b9-f774-4b2a-98e5-da8a255cfd45"),
                            Competence = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 12m,
                            Range = 3,
                            Value = 3856.94m
                        },
                        new
                        {
                            Id = new Guid("d1c8f535-70ab-4ca4-9089-67302851495c"),
                            Competence = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 14m,
                            Range = 4,
                            Value = 7507.49m
                        },
                        new
                        {
                            Id = new Guid("d5fbdfeb-a8c3-42d5-812c-872d65588c82"),
                            Competence = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 7.5m,
                            Range = 1,
                            Value = 1412.00m
                        },
                        new
                        {
                            Id = new Guid("d91884b0-cc69-46e3-8e5f-89d4dcb4d39e"),
                            Competence = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 9m,
                            Range = 2,
                            Value = 2666.68m
                        },
                        new
                        {
                            Id = new Guid("e5545b95-0f49-457d-a958-f4bc65caa6cd"),
                            Competence = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 12m,
                            Range = 3,
                            Value = 4000.03m
                        },
                        new
                        {
                            Id = new Guid("eb204e7a-5a7f-44e0-9224-833b74f4c173"),
                            Competence = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 14m,
                            Range = 4,
                            Value = 7786.02m
                        },
                        new
                        {
                            Id = new Guid("f5c4d84a-2e79-47ea-9949-e9f4ede99ce8"),
                            Competence = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 7.5m,
                            Range = 1,
                            Value = 1518.00m
                        },
                        new
                        {
                            Id = new Guid("fd49c72a-8b9d-4221-a144-0acc75ab3b44"),
                            Competence = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 9m,
                            Range = 2,
                            Value = 2793.88m
                        },
                        new
                        {
                            Id = new Guid("ff88a34a-9fa4-47b6-996e-41bb5c9bd374"),
                            Competence = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 12m,
                            Range = 3,
                            Value = 4190.83m
                        },
                        new
                        {
                            Id = new Guid("ff8b28ec-a94f-4291-ae7d-2ac3de353ce1"),
                            Competence = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 14m,
                            Range = 4,
                            Value = 8157.41m
                        });
                });

            modelBuilder.Entity("CalculoImposto.Domain.Entities.Irrf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Competence")
                        .HasColumnType("DATE");

                    b.Property<decimal>("Deduction")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("Percent")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<int>("Range")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Irrf", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("145774d6-2289-42d0-9060-2cb73a3681c6"),
                            Competence = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 0m,
                            Percent = 0m,
                            Range = 1,
                            Value = 1903.98m
                        },
                        new
                        {
                            Id = new Guid("19833513-67a2-4db5-91f5-ec212bd5e397"),
                            Competence = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 142.80m,
                            Percent = 7.50m,
                            Range = 2,
                            Value = 2826.65m
                        },
                        new
                        {
                            Id = new Guid("23dcc1ce-cdff-424a-ba82-caf29591244c"),
                            Competence = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 354.80m,
                            Percent = 15m,
                            Range = 3,
                            Value = 3751.05m
                        },
                        new
                        {
                            Id = new Guid("3d6487f9-8c14-475a-bda2-8346ca65baaa"),
                            Competence = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 636.13m,
                            Percent = 22.50m,
                            Range = 4,
                            Value = 4664.68m
                        },
                        new
                        {
                            Id = new Guid("473a63a2-b1a0-4721-bee4-5fbc3d27a7e3"),
                            Competence = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 869.36m,
                            Percent = 27.50m,
                            Range = 5,
                            Value = 99999999999.99m
                        },
                        new
                        {
                            Id = new Guid("5489d21d-c596-486e-a506-e77589fc9989"),
                            Competence = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 0m,
                            Percent = 0m,
                            Range = 1,
                            Value = 2112.00m
                        },
                        new
                        {
                            Id = new Guid("7468fb2e-58bb-4e4b-bbc6-9de0e87438ea"),
                            Competence = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 158.40m,
                            Percent = 7.50m,
                            Range = 2,
                            Value = 2826.65m
                        },
                        new
                        {
                            Id = new Guid("7d50c7d0-6576-4f6c-b348-017062ad5837"),
                            Competence = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 370.40m,
                            Percent = 15m,
                            Range = 3,
                            Value = 3751.05m
                        },
                        new
                        {
                            Id = new Guid("9c978ea5-472a-4e71-a082-73a5d5d99b74"),
                            Competence = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 651.73m,
                            Percent = 22.50m,
                            Range = 4,
                            Value = 4664.68m
                        },
                        new
                        {
                            Id = new Guid("9fe85d20-3fd8-4e62-90ba-2807eaa9abf3"),
                            Competence = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 884.96m,
                            Percent = 27.50m,
                            Range = 5,
                            Value = 99999999999.99m
                        },
                        new
                        {
                            Id = new Guid("a7df5997-6db5-4a51-8da1-a0703ac05ecd"),
                            Competence = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 0m,
                            Percent = 0m,
                            Range = 1,
                            Value = 2259.20m
                        },
                        new
                        {
                            Id = new Guid("affd90a2-0372-45ff-af40-ee69d3e343a0"),
                            Competence = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 169.44m,
                            Percent = 7.50m,
                            Range = 2,
                            Value = 2826.65m
                        },
                        new
                        {
                            Id = new Guid("bcab32f7-35f1-4dc4-898c-2d36ee0af95c"),
                            Competence = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 381.44m,
                            Percent = 15m,
                            Range = 3,
                            Value = 3751.05m
                        },
                        new
                        {
                            Id = new Guid("eed864b0-2bc9-455c-beb8-bae000da7077"),
                            Competence = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 662.77m,
                            Percent = 22.50m,
                            Range = 4,
                            Value = 4664.68m
                        },
                        new
                        {
                            Id = new Guid("f544a765-e333-4242-aa9a-c7bece8efed8"),
                            Competence = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 896.00m,
                            Percent = 27.50m,
                            Range = 5,
                            Value = 99999999999.99m
                        });
                });

            modelBuilder.Entity("CalculoImposto.Domain.Entities.Simplificado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Competence")
                        .HasColumnType("DATE");

                    b.Property<decimal>("Value")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Simplificado", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("300ec55a-a5b0-411b-be64-627db7608037"),
                            Competence = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 528.00m
                        },
                        new
                        {
                            Id = new Guid("9db4331e-9735-403d-b2f7-6bbeb8942556"),
                            Competence = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 564.80m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
