// <auto-generated />
using System;
using CalculoImposto.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculoImposto.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalculoImposto.Domain.Entities.Dependente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Competence")
                        .HasColumnType("DATE");

                    b.Property<decimal>("Value")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Dependente", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bfa5e22d-0688-4c0b-88c3-828e0d9202eb"),
                            Competence = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 189.59m
                        });
                });

            modelBuilder.Entity("CalculoImposto.Domain.Entities.DescontoMinimo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Competence")
                        .HasColumnType("DATE");

                    b.Property<decimal>("Value")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.ToTable("DescontoMinimo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0441894f-fa4b-45ec-b9b6-c992ea9763a6"),
                            Competence = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 10m
                        });
                });

            modelBuilder.Entity("CalculoImposto.Domain.Entities.Inss", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Competence")
                        .HasColumnType("DATE");

                    b.Property<decimal>("Percent")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<int>("Range")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Inss", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("06fb76d6-c14b-4eaf-af1a-5180d4bee488"),
                            Competence = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 7.5m,
                            Range = 1,
                            Value = 1045.00m
                        },
                        new
                        {
                            Id = new Guid("1d1a159e-ea80-4e2b-b2b9-f3bd3a64a0ad"),
                            Competence = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 9m,
                            Range = 2,
                            Value = 2089.60m
                        },
                        new
                        {
                            Id = new Guid("97ba531f-fc3d-4316-bb02-6e9fdf5130e5"),
                            Competence = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 12m,
                            Range = 3,
                            Value = 3134.40m
                        },
                        new
                        {
                            Id = new Guid("9184caba-60df-4b36-9ac8-9a4d9650243a"),
                            Competence = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 14m,
                            Range = 4,
                            Value = 6101.06m
                        },
                        new
                        {
                            Id = new Guid("522076f9-37f0-449c-85b6-53a19367c9f8"),
                            Competence = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 7.5m,
                            Range = 1,
                            Value = 1212.00m
                        },
                        new
                        {
                            Id = new Guid("d854e1c7-86af-43c1-b39c-947e4144076d"),
                            Competence = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 9m,
                            Range = 2,
                            Value = 2452.67m
                        },
                        new
                        {
                            Id = new Guid("9c93a24a-e1a1-43a2-a95b-a2015ec147b8"),
                            Competence = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 12m,
                            Range = 3,
                            Value = 3679.00m
                        },
                        new
                        {
                            Id = new Guid("3621735d-242e-430f-abaf-36fd19f26ba4"),
                            Competence = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 14m,
                            Range = 4,
                            Value = 7087.22m
                        },
                        new
                        {
                            Id = new Guid("7ec363e9-0019-4f69-9e0a-441c6424c48d"),
                            Competence = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 7.5m,
                            Range = 1,
                            Value = 1302.00m
                        },
                        new
                        {
                            Id = new Guid("1cf40be4-4a34-4894-b679-653c10b7a7a2"),
                            Competence = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 9m,
                            Range = 2,
                            Value = 2571.29m
                        },
                        new
                        {
                            Id = new Guid("c1dd95c8-b624-48f1-b7e8-fbc0b0b4a16e"),
                            Competence = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 12m,
                            Range = 3,
                            Value = 3856.94m
                        },
                        new
                        {
                            Id = new Guid("cbcfd40e-46c1-40ac-9029-06f7b951d418"),
                            Competence = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 14m,
                            Range = 4,
                            Value = 7507.49m
                        },
                        new
                        {
                            Id = new Guid("2699e354-a7b6-4e6f-9c89-10cb63b6a51f"),
                            Competence = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 7.5m,
                            Range = 1,
                            Value = 1320.00m
                        },
                        new
                        {
                            Id = new Guid("8ef9c1d1-b976-4882-8835-cd1774e8ede0"),
                            Competence = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 9m,
                            Range = 2,
                            Value = 2571.29m
                        },
                        new
                        {
                            Id = new Guid("d15e654a-abc2-47fd-81a7-e620264c4d4c"),
                            Competence = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 12m,
                            Range = 3,
                            Value = 3856.94m
                        },
                        new
                        {
                            Id = new Guid("32379205-7ee1-4fe1-b3c8-f9e7c3bcc443"),
                            Competence = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 14m,
                            Range = 4,
                            Value = 7507.49m
                        },
                        new
                        {
                            Id = new Guid("e6324c1f-465d-454e-9b01-6a3c28c354b2"),
                            Competence = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 7.5m,
                            Range = 1,
                            Value = 1412.00m
                        },
                        new
                        {
                            Id = new Guid("52a39bc8-1094-48aa-849d-ba1720fe8464"),
                            Competence = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 9m,
                            Range = 2,
                            Value = 2666.68m
                        },
                        new
                        {
                            Id = new Guid("64ef6174-9bea-432f-83b1-837bf018c70c"),
                            Competence = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 12m,
                            Range = 3,
                            Value = 4000.03m
                        },
                        new
                        {
                            Id = new Guid("9089029d-a720-424f-933e-1185bd6cfb75"),
                            Competence = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 14m,
                            Range = 4,
                            Value = 7786.02m
                        },
                        new
                        {
                            Id = new Guid("defdc03a-0c30-491e-b627-96e16be5f0d8"),
                            Competence = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 7.5m,
                            Range = 1,
                            Value = 1518.00m
                        },
                        new
                        {
                            Id = new Guid("d7eac449-cc29-4108-842e-b6bb2e689231"),
                            Competence = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 9m,
                            Range = 2,
                            Value = 2793.88m
                        },
                        new
                        {
                            Id = new Guid("3ae4f324-9e4d-4763-ba7f-5ef36de7a60c"),
                            Competence = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 12m,
                            Range = 3,
                            Value = 4190.83m
                        },
                        new
                        {
                            Id = new Guid("a84980ca-ffb5-4841-a659-1d287c84b6ac"),
                            Competence = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Percent = 14m,
                            Range = 4,
                            Value = 8157.41m
                        });
                });

            modelBuilder.Entity("CalculoImposto.Domain.Entities.Irrf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Competence")
                        .HasColumnType("DATE");

                    b.Property<decimal>("Deduction")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("Percent")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<int>("Range")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Irrf", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3fa92be7-a944-46d8-9771-1cc947357619"),
                            Competence = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 0m,
                            Percent = 0m,
                            Range = 1,
                            Value = 1903.98m
                        },
                        new
                        {
                            Id = new Guid("77c42494-30a9-4e9c-aacd-02eb69b0f7c6"),
                            Competence = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 142.80m,
                            Percent = 7.50m,
                            Range = 2,
                            Value = 2826.65m
                        },
                        new
                        {
                            Id = new Guid("c0dc33a5-4a18-4f67-9e5f-2222fe7d9355"),
                            Competence = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 354.80m,
                            Percent = 15m,
                            Range = 3,
                            Value = 3751.05m
                        },
                        new
                        {
                            Id = new Guid("6ded96d0-a5ad-4bf4-aa4a-125b2961d728"),
                            Competence = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 636.13m,
                            Percent = 22.50m,
                            Range = 4,
                            Value = 4664.68m
                        },
                        new
                        {
                            Id = new Guid("5f7acfef-f69b-42cf-bb63-5aabf267346c"),
                            Competence = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 869.36m,
                            Percent = 27.50m,
                            Range = 5,
                            Value = 99999999999.99m
                        },
                        new
                        {
                            Id = new Guid("6261e0f2-bdd3-4bef-9dc3-21e7bebd0cec"),
                            Competence = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 0m,
                            Percent = 0m,
                            Range = 1,
                            Value = 2112.00m
                        },
                        new
                        {
                            Id = new Guid("d64284dc-ccd2-4e84-9540-20297356a151"),
                            Competence = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 158.40m,
                            Percent = 7.50m,
                            Range = 2,
                            Value = 2826.65m
                        },
                        new
                        {
                            Id = new Guid("39ce6a17-8749-4f02-ae4e-0731c7225e7f"),
                            Competence = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 370.40m,
                            Percent = 15m,
                            Range = 3,
                            Value = 3751.05m
                        },
                        new
                        {
                            Id = new Guid("bb940995-0624-41b3-9f79-1c027665f5b7"),
                            Competence = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 651.73m,
                            Percent = 22.50m,
                            Range = 4,
                            Value = 4664.68m
                        },
                        new
                        {
                            Id = new Guid("534f8981-fd71-40ae-ba18-dca32699ee7b"),
                            Competence = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 884.96m,
                            Percent = 27.50m,
                            Range = 5,
                            Value = 99999999999.99m
                        },
                        new
                        {
                            Id = new Guid("844ae8fd-7879-4b6f-ac93-bc1859128c65"),
                            Competence = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 0m,
                            Percent = 0m,
                            Range = 1,
                            Value = 2259.20m
                        },
                        new
                        {
                            Id = new Guid("43c4ae8b-5d5c-44b3-b71a-52b95673fb6d"),
                            Competence = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 169.44m,
                            Percent = 7.50m,
                            Range = 2,
                            Value = 2826.65m
                        },
                        new
                        {
                            Id = new Guid("474fa28a-8c6f-44a5-8b85-2528837df526"),
                            Competence = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 381.44m,
                            Percent = 15m,
                            Range = 3,
                            Value = 3751.05m
                        },
                        new
                        {
                            Id = new Guid("553eb4c1-867a-4289-ade4-7918c8f3ffdd"),
                            Competence = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 662.77m,
                            Percent = 22.50m,
                            Range = 4,
                            Value = 4664.68m
                        },
                        new
                        {
                            Id = new Guid("11ef9768-983d-42ee-96fd-27f84707dcd9"),
                            Competence = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deduction = 896.00m,
                            Percent = 27.50m,
                            Range = 5,
                            Value = 99999999999.99m
                        });
                });

            modelBuilder.Entity("CalculoImposto.Domain.Entities.Simplificado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Competence")
                        .HasColumnType("DATE");

                    b.Property<decimal>("Value")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Simplificado", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("368acce8-c097-495c-b28b-3b6ab4285219"),
                            Competence = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 528.00m
                        },
                        new
                        {
                            Id = new Guid("93fa5b6d-5bdf-4380-af47-523c3bbda1b9"),
                            Competence = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 564.80m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
