// <auto-generated />
using System;
using CalculoImposto.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculoImposto.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalculoImposto.Domain.Entities.Dependente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("DATE");

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Dependente", (string)null);
                });

            modelBuilder.Entity("CalculoImposto.Domain.Entities.DescontoMinimo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("DATE");

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.ToTable("DescontoMinimo", (string)null);
                });

            modelBuilder.Entity("CalculoImposto.Domain.Entities.Inss", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("DATE");

                    b.Property<int>("Faixa")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Porcentagem")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Inss", (string)null);
                });

            modelBuilder.Entity("CalculoImposto.Domain.Entities.Irrf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("DATE");

                    b.Property<decimal>("Deducao")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("Faixa")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Porcentagem")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Irrf", (string)null);
                });

            modelBuilder.Entity("CalculoImposto.Domain.Entities.Simplificado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("DATE");

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Simplificado", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
